updated ios test yaml

diff --git a/.github/workflows/ios-test.yml b/.github/workflows/ios-test.yml
--- a/.github/workflows/ios-test.yml
+++ b/.github/workflows/ios-test.yml
@@ -143,7 +143,13 @@ jobs:
           node-version: '18'
 
       - name: Install dependencies
-        run: npm ci
+        run: |
+            echo "Attempting npm ci..."
+            if ! npm ci; then
+              echo "npm ci failed, falling back to npm install"
+              npm install --legacy-peer-deps
+            fi
+        
 
       - name: Verify connected iOS devices
         run: |
